function formValidate(){
    let evType = document.getElementById("eventType").value;
    let evTitle = document.getElementById("eventTitle").value;
    let evDatesFrom = document.getElementById("eventDates").value;
    let evDatesTo = document.getElementById("eventDates1").value;
    let postDate = document.getElementById("postingDate").value;
    let req = document.getElementById("required").value;
    let famProg = document.getElementById("familyPrograms").value;
    let autoGenEmails = document.getElementById("autoGeneratedEmails").value;
    let cntct = document.getElementById("contact").value;
    let hsting = document.getElementById("hosting").value;

    if(document.getElementById("required").checked){
        req = document.getElementById("required").value = "checked";
    }else{
        req = document.getElementById("required").value = "unchecked";
    }

    if(document.getElementById("familyPrograms").checked){
        famProg = document.getElementById("familyPrograms").value = "checked";
    }else{
        famProg = document.getElementById("familyPrograms").value = "unchecked";
    }

    if(document.getElementById("autoGeneratedEmails").checked){
        autoGenEmails = document.getElementById("autoGeneratedEmails").value = "checked";
    }else{
        autoGenEmails = document.getElementById("autoGeneratedEmails").value = "unchecked";
    }

    if(document.getElementById("contact").checked){
        cntct = document.getElementById("contact").value = "checked";
    }else{
        cntct = document.getElementById("contact").value = "unchecked";
    }

    if(document.getElementById("hosting").checked){
        hsting = document.getElementById("hosting").value = "checked";
    }else{
        hsting = document.getElementById("hosting").value = "unchecked";
    }

    if(((evType == "") && (evTitle == "") && (evDatesFrom == "") && (evDatesTo == "") && (postDate == ""))){
        alert("Your missing input fields: Event Type, Event Title, Event Dates, and Posting Date");        
    }else if(((evType == "") && (evTitle == "") && (evDatesFrom == "") && (evDatesTo == ""))){
        alert("Your missing input fields: Event Type, Event Title, and Event Dates");        
    }else if(((evType == "") && (evTitle == ""))){
        alert("Your missing input fields: Event Type, and Event Title");        
    }else if((evType == "")){
        alert("Your missing input fields: Event Type");        
    }else if(((evType != "") && (evTitle != "") && (evDatesFrom != "") && (evDatesTo != "") && (postDate != ""))){
        alert("Form submitted succesfully! For more information, Contact us: 09063721400 or Email us through: eventsandstyles@gmail.com Thank you and Have a good day!")
    }
}